### PR TITLE
2017 data model updates

### PR DESCRIPTION
**Pull request by tkellen**
addresses gh-180

### CODE REVIEW

**Comment by tkellen** [comment]
@bmac All commands that were affected by our 2017 data model adjustments have been fixed or updated to accurately notate this. I've cordoned off Fridays this year for supporting our internal infrastructure so you can expect this to be addressed by January 13th.

*Please* ping me if I fail to meet this goal and you are actively wanting this information. I think it is critical that our team members have unfettered access to the metrics around the goals we set as a company but I am juggling *many* responsibilities.

**Comment by JasminRuth** [comment]
Jasmin is working with Jory and Mary this week to update metrics and targets to align them with the 2017 Strategic Planning the week of January 10th. Jasmin will provide status update next Monday January 16th 2017.

**Comment by tkellen** [comment]
Hi @JasminRuth! Just checking in to see how this is coming

**Comment by JasminRuth** [comment]
Please update the ongoing goal of our weighted pipeline value to be $1,500,000 for all quarters of 2017 in the robocoup command "Pipeline".

**Comment by JasminRuth** [comment]
Please remove "Our goal is currently *80%* of our *21* billable team members utilized on billable B2B projects." from the robocoup command "utilization" and re-enable the command. We are no longer using the global % as a metric but we still want to show bocoupers data about their time.

**Comment by tkellen** [comment]
closing as wontfix.

**Pull request closed without merging**
